const styles = {
  container: { 
    flex: 1,
    alignSelf: 'center',
    // alignItems: 'center',
    //height: 80,
    // maxHeight: '100%',
    maxWidth: '100%',
    // height: 35,
    marginTop: 0,
    flexDirection: 'row',    
    borderRadius: 20,
    //  borderWidth: 2, borderColor: 'red',    
   },
   HomeImage:{
    flex: 1,
    alignSelf: 'center',
    // marginVertical  : 10,
    // marginTop: -50,
    maxWidth: '20%',
    // height:20,
    // alignItems: 'flex-start',
    marginLeft: 0,
    marginTop: 0,
    // borderWidth: 2, borderColor: 'red',     
   },
  holder: {  
    flex: 1,
    marginVertical: 0,
    // height: 20,
    // width: 60,  
    // marginTop: 10,
    // marginLeft: 105,
    justifyContent: 'center',    
    // borderWidth: 2, borderColor: 'red',            
  },
  Hometext: {
    // flex: 1,
    textAlign: 'center',
    fontSize: 13,
    // marginLeft: 13,
    marginTop: -12,
    // borderWidth: 2, borderColor: 'red',
  },       
  OrdersImage:{
    flex: 1,    
    alignSelf: 'center',
    // marginVertical  : -10,
    maxWidth: '25%',
    //height:22,
    // marginLeft: 20,
    marginTop: 0,
    // borderWidth: 2, borderColor: 'red',
  },
  holder1: {  
    flex: 1,
    marginVertical: 0,
    // height: 20,
    // width: 50,  
    // marginTop: 5,
    // marginLeft: -5, 
    justifyContent: 'center',
    // borderWidth: 2, borderColor: 'red',          
  }, 
  Orderstext: {
    // flex: 1,
    textAlign: 'center',
    fontSize: 13,
    // marginLeft: -40,      
    marginTop: -10,      
    // borderWidth: 2, borderColor: 'red',
  }, 
  ExploreImage:{
    flex: 1,    
    alignSelf: 'center',
    // marginVertical  : -10,
    maxWidth: '20%',
    // width:20,
    // height:20,
    marginLeft: 5,
    marginTop: 0,
    // borderWidth: 2, borderColor: 'red',
  },
  holder2: {  
    flex: 1,
    marginVertical: 0,
    // height: 15,
    // width: 50,  
    // marginTop: 12,
    // marginLeft: -10, 
    justifyContent: 'center',
    // borderWidth: 1, borderColor: 'red',          
  }, 
  Exploretext: {
    // flex: 1,
    textAlign: 'center',
    fontSize: 13,
    marginLeft: 12,      
    marginTop: -10,
    // width: 40,
    // borderWidth: 2, borderColor: 'red',
  }, 
  ProfileImage:{
    flex: 1,    
    alignSelf: 'center',
    // marginVertical  : -10,
    maxWidth: '20%',
    // width: 40,
    // height: 40,
    // marginLeft: 5,
    marginTop: 0,
    // borderWidth: 2, borderColor: 'red',
  }, 
  holder3: {  
    flex: 1,
    marginVertical: 0,
    // height: 20,
    // width: 60,  
    // marginTop: 8,
    // marginLeft: -10, 
    justifyContent: 'center',
    // borderWidth: 2, borderColor: 'red',          
  },   
  Profiletext: {
    // flex: 1,
    textAlign: 'center',
    fontSize: 13,
    // marginLeft: 15,      
    marginTop: -10,
    // width: 50,
    // borderWidth: 2, borderColor: 'red',
  },      
};

export default styles;