const styles = {
    container: {
        flex: 1,
    },
    Back: {
        maxWidth: '100%',
        height: 330,
        backgroundColor: '#2cc9fe', 
        borderRadius: 100,    
        marginTop: -180,
        // borderColor: 'red', borderWidth: 2,
    },

    EditProfile: {
        color: '#fff',
        fontSize: 20,
        marginTop: -35,
        alignSelf: 'center',
        alignItems: 'center',      
    },
    Check: {
        color: '#fff',
        width: 170,
        fontSize: 20,
        marginTop: -30,
        marginLeft: 100, 
        alignItems: 'center',  
        // borderColor: 'red', borderWidth: 2,    
    },
    Check1: {
        color: '#fefd05',
        width: 50,
        fontSize: 15,
        marginTop: 0, 
        alignSelf: 'flex-end',
        // alignItems: 'flex-end', 
        // borderColor: '#000', borderWidth: 1,       
    },
    pad: {
        maxWidth: '100%',
        height: 150,
        backgroundColor: '#fff',       
        borderRadius: 100,
        alignSelf: 'center',
        // borderColor: 'red', borderWidth : 2,        
    },
    Image: {
        maxWidth: '100%',
        height: 150,
        alignItems: 'center',
        // borderColor: 'red', borderWidth : 2,
    },
    Name: {
        color: 'black',
        fontWeight: 'bold',
        fontSize: 20,
        alignSelf: 'center',
        // borderColor: 'red', borderWidth : 1,
        // alignItems: 'center', 
             
    },
    Check2: {
        color: 'lightgrey',
        fontSize: 15,
        marginTop: -22,
        marginLeft: 250, 
        alignItems: 'center',      
    },
    Name1: {
        color: 'black',
        fontSize: 19,
        fontWeight: 'bold',
        marginTop: 0,
        marginLeft: 15, 
        alignSelf: 'center',      
    },
    topBackground: {
        maxWidth: '100%',
        height: 35,
        borderColor: '#000',
        borderWidth: 0.1,
        borderRadius: 1,
        marginRight: 5, 
        marginLeft: 5,        
        // borderColor: 'red', borderWidth : 2,           
    },
    Text: {        
        color: '#000',
        marginLeft: 5,
        fontSize: 15,
        marginTop: 5,
    },
    Text1: {
        color: '#A4A4A4',
        marginRight: 5,
        fontSize: 15,
        marginTop: -35,
        textAlign: 'center',
        alignSelf: 'flex-end',
    },
    Text2: {
        color: '#2cc9fe',
        marginRight: 15,
        fontSize: 15,
        marginTop: -23,
        alignSelf: 'flex-end',
    },
    topBackground1: {
        width: 155,
        height: 50,
        backgroundColor: '#eaf8fd',
        borderColor: 'white',
        borderWidth: 1,
        borderRadius: 15, 
        marginLeft: 15,        
        // borderColor: 'red', borderWidth : 2,           
    },
    Text3: {
        color: '#2cc9fe',
        fontSize: 15,
        marginTop: -21,
        marginRight: 15,
        alignSelf: 'flex-end',
    },
    topBackground2: {
        width: 155,
        height: 50,
        backgroundColor: '#eaf8fd',
        borderColor: 'white',
        borderWidth: 1,
        borderRadius: 15, 
        marginLeft: 15,        
        // borderColor: 'red', borderWidth : 2,
        marginLeft: 190,
        marginTop: -65,           
    },
    Text4: {
        color: '#2cc9fe',
        fontSize: 15,
        marginTop: -21,
        marginRight: 15,
        alignSelf: 'flex-end',
    },
    Text5: {
        color: '#2cc9fe',
        fontSize: 15,
        marginTop: -21,
        marginRight: 15,
        alignSelf: 'flex-end',
    },
    buttonproceed1: {    
        backgroundColor: '#2cc9fe',
        marginTop:  -8,
        // borderRadius: 30,
        height: 40,
        maxWidth: '100%',  
    },
    buttonproceed: {
        textAlign: 'center',
        color: '#fff',
        // alignItems: 'center',
        fontWeight: 'bold',
        fontSize: 15, 
        marginTop: 10,
    }, 
};    

export default styles;