const styles = {
    container: {
        flex: 1,
        // alignItems: 'center',
        // justifyContent: 'center',
        backgroundColor: "#fff",        
        // height: 0, 
        //height,        
    },


    //  container : {
    //     flexGrow: 1,
    //     justifyContent: 'flex-end',
    //     alignItems: 'center',        
    // },
    // logoText: {
    //     marginVertical: 30,
    //     fontSize: 20,
    //     color: '#fff',
    //     marginTop: 10,
    //     marginBottom: 100,
    // },
    signupTextCont: {
        // flex: 0.2,
        justifyContent: 'center',       
        flexDirection: 'row',
        marginTop: 0,     
    },
    singupText: {
        // flex: 0.5,
        color: 'grey',
        fontSize: 14, 
        marginTop: 2,       
    },
    singupButton: {
        color: 'grey',
        fontSize: 15,
        fontWeight: '500',
        marginTop: 0,
    },
    // logobackground: {
    //     width: 360, //width,
    //     height: 300,        
    //     justifyContent: 'center',
    //     alignItems: 'center',
    //     // marginTop: 100,
    //     backgroundColor: '#2cc9fe',
    // },   

    logobackground: {
        flex: 0.7,
        // flexGrow: 0.5,
        maxWidth: '100%',
        // height: 120,
        // maxHeight: '50%',
        // marginTop: 20,         
        // justifyContent: 'center',
        // alignItems: 'center',        
        backgroundColor: '#2cc9fe',
    },
    // inputBox: {
    //     width: 280,
    //     marginTop: -17,       
    //     backgroundColor: 'rgba(255, 255, 255, 0.3)',
    //     borderRadius: 25,
    //     paddingHorizontal: 10,
    //     fontSize: 16,
    //     color: '#000',
    //     marginVertical: 3,        
    // },

    inputBox: {
        flex: 0.5,
        width: 280,
        // marginTop: -20,       
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        borderRadius: 25,
        // paddingHorizontal: 10,
        fontSize: 16,
        color: '#000',
        // marginVertical: 3,
        // paddingBottom: 10,               
    },
    inputBox1: {
        flex: 0.3,
        width: 280,
        marginTop: -15,       
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        borderRadius: 25,
        // paddingHorizontal: 10,
        fontSize: 16,
        color: '#000',
        // marginVertical: 3,
        // paddingBottom: 10,               
    },



    // label:{
    //     marginLeft: 15,
    //     color: 'lightgrey',
    //     marginTop: 20,
    // },
    label:{
        flex: 0.5,
        marginLeft: 10,
        color: '#000',
        marginTop: 0,
    },
    // labelp:{
    //     marginLeft: 15,
    //     color: 'lightgrey',
    //     marginTop: 30,
    // },

    labelp:{
        flex: 0.5,
        marginLeft: 10,
        color: '#000',
        marginTop: 0,
    },


    // user: {
    //     width: 20,
    //     height: 18,        
    //     marginLeft: 240, 
    //     marginTop: -20,
    //     marginVertical: 0,          
    // },
    user: {
        flex: 0,
        width: 20,
        height: 20,       
        alignSelf: 'flex-end',
        marginRight: 25,   
        // marginTop: 20,      
        // marginLeft: 240, 
        marginTop: -33, 
        // marginVertical: 0,          
    },
    // email:{
    //     width: 23,
    //     height: 18,
    //     marginTop: -10,
    //     marginLeft: 240,
    // },
    // pass: {
    //     width:23,
    //     height: 18,
    //     marginTop: -20,
    //     marginLeft: 240,           
    // },
    // passp: {
    //     width:23,
    //     height: 18,
    //     marginTop: -20,
    //     marginLeft: 240,           
    // },

    passp: {
        flex: 0,
        width: 20,
        height: 20,
        alignSelf: 'flex-end',
        marginRight: 25, 
        // flexDirection: 'row',
        marginTop: -33,
        // marginLeft: 240,           
    },
    button: {
        flex: 0,
        width: 250,
        height: 45,
        backgroundColor: "#2cc9fe",
        // marginVertical: 10,
        // paddingVertical: 12,
        borderRadius: 25, 
        // marginTop: -50,
        // marginLeft: 50,
        // marginRight: 100,
        alignItems: 'center',
        // justifyContent: 'center',
        alignSelf: 'center',
        // alignContent: 'space-between',
        // marginTop: 50,     
    }, 
    buttonText: {
        marginTop: 10,
        fontSize: 15,
        // alignSelf: 'center',
        fontWeight: 'bold',
        color: '#fff',
        textAlign: 'center',
        borderRadius: 20,        
    },
    // textbackground: {
    //     backgroundColor: '#fff',
    //     borderRadius: 10,
    //     height: 200,
    //     marginLeft: 30,
    //     marginRight: 30,
    //     marginTop: -70,
    // }, 
    textbackground: {
        flex: 0,
        // flexGrow: 1,
        alignSelf: 'center',
        alignItems: 'center',
        // justifyContent: 'center',
        backgroundColor: '#F8F9F9',
        borderRadius: 10,
        // maxWidth: '100%',
        width: 355,
        height: 150,
        // marginTop: -10,  
        // borderColor: '#000',
        // borderWidth: 2,
        marginTop: -20,        
    }, 

 

};

export default styles;