const styles = {
    container: {
        flex: 1,        
    },
    headertext: {
        marginLeft: 140,
        marginTop: 25,
        alignItems: 'center',
        justifyContent: 'center', 
        fontSize: 20,
        color: 'white',        
    },
    topBackground: {
        width: 360, //width,
        height: 255,
        backgroundColor: '#2cc9fe',
    },
    textbackground: {
        backgroundColor: '#fff',
        borderRadius: 25,
        width: 340,
        height: 40,
        marginTop: 60,
        marginLeft: 10,      
    },  
    label:{
        marginLeft: 35,
        color: 'lightgrey',
        marginTop: 10,
    },
    inputBox: {
        width: 280,
        marginTop: -20,       
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        borderRadius: 25,
        paddingHorizontal: 10,
        fontSize: 17,
        color: '#000',
        marginVertical: 5,
        marginLeft: 30,        
    },
    Search: {
        width: 20,
        height: 20,        
        marginLeft: 27,
        marginTop: -170,
        borderRadius: 1,
    },
    hairecare: {
        width: 150,
        height: 120,
        backgroundColor: '#fff',
        borderColor: '#d1d5dc',
        borderWidth: 1,
        borderRadius: 15,
        marginLeft: 20,
        marginTop: -250,        
    },
    hairecareImage1: {
        width: 50,
        height: 50,
        marginLeft: 50,
        alignItems: 'center',
        marginTop: 10,  
    },
    skincare: {
        width: 150,
        height: 120,
        backgroundColor: '#fff',
        borderColor: '#d1d5dc',
        borderWidth: 1,
        borderRadius: 15,
        marginLeft: 190,
        marginTop: -126,        
    },
    skincareImage1: {
        width: 50,
        height: 50,
        marginLeft: 50,
        alignItems: 'center',
        marginTop: 10,        
    },
    skincareText: {
        color: 'black',
        alignContent: 'center',
        flex:1,
        justifyContent: 'center',        
        paddingLeft: 160,
        paddingTop: 50,    
    },
    bodycare: {
        width: 320,
        height: 120,
        backgroundColor: '#fff',
        borderColor: '#d1d5dc',
        borderWidth: 1,
        borderRadius: 15,
        marginLeft: 20,
    },
    bodycareImage1: {
        width: 50,
        height: 50,
        marginLeft: 130,
        alignItems: 'center',
        marginTop: 10,        
    },
    bodycareText: {
        color: 'black',
        marginLeft: 96,
        fontSize: 30,
        marginBottom: 10,
    },
};

export default styles;