import { Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = {
    container: {
        flex: 1,
        // flexDirection: 'column',
        // alignItems: 'center',
        // justifyContent: 'center',
        // alignContent: 'center',
        backgroundColor: "#fff",        
    },
    Signup: {
        flex: 1,
        // alignContent: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 20,
        alignSelf: 'center',
        // alignItems: 'flex-end',
    },
    signupFacebook : {
        flex: 1.5,
        // alignContent: 'center',
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 10,
        alignSelf: 'center',
        // alignItems: 'flex-end',
    },
    signupTextCont : {
        flex: 1,
        // flexGrow: 1,
        // alignItems: 'flex-end',
        justifyContent: 'center',
        // paddingVertical: 16,
        flexDirection: 'row',
        marginTop: 10,
    },
    singupText: {
        color: 'grey',
        fontSize: 13,       
    },
    singupButton: {
        color: 'black',
        fontSize: 15,
        fontWeight: '500',
    },  
    button1: {
        // flex: 1,
        width: 250,
        height: 50,
        backgroundColor: "#3b5998",
        // marginVertical: 10,
        // paddingVertical: 12,
        // marginLeft: 55,
        borderRadius: 25,
        marginTop: -3,
        alignItems: 'center',
        alignContent: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        // alignItems: 'flex-end',
    },
    buttonText1: {
        fontSize: 16,
        fontWeight: '500',
        color: '#fff',
        textAlign: 'center',
        borderRadius: 20,        
    },
    logobackground: {
        flex: 1,
        flexGrow: 2,
        maxWidth: '100%',
        maxHeight: '55%',        
        // justifyContent: 'center',
        // alignItems: 'center',        
        backgroundColor: '#2cc9fe',
        // marginTop: 5,
        
    },
    context : {
        flex: 1,
        flexGrow: 2.5,
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: -15,   
        maxWidth: '100%',
        // height: 100,
          
    },
    inputBox: {
        flex: 0.5,
        width: 350,
        // maxWidth: '50%',
        marginTop: 0,       
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        borderRadius: 25,
        // paddingHorizontal: 10,
        fontSize: 16,
        color: '#000',
        // marginVertical: 3,
        // paddingBottom: 10,   
        // borderColor: 'red', borderWidth: 2,            
    },
    inputBox1: {
        flex: 0.5,
        width: 280,
        marginTop: 0,       
        backgroundColor: 'rgba(255, 255, 255, 0.3)',
        borderRadius: 25,
        // paddingHorizontal: 10,
        fontSize: 16,
        color: '#000',
        // marginVertical: 3,
        // paddingBottom: 10,      
        // borderColor: 'red', borderWidth: 2,  
    },
    label:{
        flex: 0.3,
        marginLeft: 10,
        color: '#000',
        marginTop: 0,
    },
    labele:{
        flex: 0.3,
        marginLeft: 10,
        color: '#000',
        marginTop: 0,
    },
    labelp:{
        flex: 0.3,
        marginLeft: 10,
        color: '#000',
        marginTop: 0,
    },
    user: {
        // flex: 0.3,
        width: 18,
        height: 18,     
        alignSelf: 'flex-end',           
        // marginLeft: 240, 
        marginTop: -30, 
        // marginVertical: 0,    
        // borderColor: 'red', borderWidth: 2,        
    },
    email:{
        // flex: 0.3,
        width: 22,
        height: 18,
        marginTop: -30,
        alignSelf: 'flex-end',
        // marginLeft: 240,
        // borderColor: 'red', borderWidth: 2,
    },
    pass: {
        // flex: 0.3,
        width:23,
        height: 18,
        marginTop: -30,
        // marginLeft: 240,
        alignSelf: 'flex-end',           
    },
    button2: {
        // flex: 0.5,
        width: 230,
        height: 40,
        backgroundColor: "#2cc9fe",
        alignSelf: 'center',
        alignItems: 'center',
        // marginVertical: 10,
        // paddingVertical: 12,
        borderRadius: 25, 
        margin: 0,
        marginTop: 0,
        // marginLeft: 100,
        // marginRight: 100       
    }, 
    buttonText2: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#fff',
        textAlign: 'center',
        borderRadius: 20, 
        alignItems: 'center',  
        justifyContent: 'center',  
        marginTop: 8,   
    },
    fbbutton: {
        width: 230,
        height: 40,
        backgroundColor: "#2cc9fe",
        alignSelf: 'center',
        alignItems: 'center',
        // marginVertical: 10,
        // paddingVertical: 12,
        borderRadius: 25, 
        margin: 0,
        marginTop: -10,  
},
    textbackground: {
        flex: 1,
        // flexGrow: 3,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#fff',
        borderRadius: 10,
        width: '99%',
        marginRight: 10,
        marginLeft: 10,
        // height: 125,
        // marginTop: -10,  
        // borderColor: 'red',
        // borderWidth: 2,
        marginTop: -5,        
    }, 
    
    button: {
        flex: 0.3,
        width: 300,
        height: 60,
        backgroundColor: "#2cc9fe",
        // marginVertical: 10,
        // paddingVertical: 15,
        borderRadius: 30,
        // marginTop: -110,
        alignItems: 'center',
        justifyContent: 'center',
        alignSelf: 'center',
        margin: 20,

    },

    buttonText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#ffffff',
        textAlign: 'center'
    },

    buttonsignin: {
        flex: 0.3,
        width: 300,
        height: 60,
        backgroundColor: "#fff",
        borderWidth: 2,
        borderColor: "#2cc9fe",
        // marginVertical: 10,
        // paddingVertical: 15,
        borderRadius: 30, 
        alignSelf: 'center', 
        margin: 20,      
    },
  
      buttonTextsignin: {
        fontSize: 16,
        fontWeight: '500',
        color: '#2cc9fe',
        textAlign: 'center'
    },
};

export default styles;